### ISSUE TITLE
hu (Hungarian - magyar) completed in Crowdin

### ISSUE THREAD

**Issue by ovari** [citizenos/etherpad_translations#33]
The hu (Hungarian - magyar) translation is 100% complete in Crowdin
https://crowdin.com/project/citizen-os-etherpad

Could you please merge hu into your project?

Thank you

**Comment by ovari** [comment]
@ilmartyrk does this merge merge everywhere, including https://github.com/citizenos/ep_translations

Thank you

**Comment by ilmartyrk** [comment]
@ovari merged the translations, this project is just for storing all translations we use in our project to import these into your setup, you'll need to add ep_translations plugin and add into settings.json  

`"ep_translations": {  
    "type": "git", 
    "path": "git://github.com/citizenos/etherpad_translations.git", 
    "savePath": "/tmp/ep_translations"
 }`

**Comment by ovari** [comment]
It seems there are still English strings in https://github.com/citizenos/etherpad_translations/pull/34/commits/28a8966ff03eb8074afcc01457d2754fe565525a

Can your project please be updated with the translations from upstream? There are new `hu` locale merges as shown at https://github.com/ether/etherpad-lite/issues/4202#issuecomment-666286170

Thank you

**Comment by ovari** [comment]
> import these into your setup

Thank you for your message; unfortunately we don't have a setup. We thought the `hu` locale would help with your project.

**Comment by ovari** [comment]
@ilmartyrk `Hungarian`, at https://crowdin.com/project/citizen-os-etherpad, says `Approved: 91%`.

How can `Approved: 100%` be achieved?

Thank you
